### ISSUE TITLE
On Install

### ISSUE THREAD

**Issue by gOOvER** [IsekaiDevPlugins/de.isekaidev.discord.wbbBridge#1] opened 2017-06-25 15:42 UTC
```
Error

Error Type:
wcf\system\exception\SystemException
Error Message:
Cannot override existing category 'discord'
File:
*/lib/system/package/plugin/AbstractOptionPackageInstallationPlugin.class.php (251)
Stack Trace:
#0 */lib/system/package/plugin/AbstractOptionPackageInstallationPlugin.class.php (148):
wcf\system\package\plugin\AbstractOptionPackageInstallationPlugin->saveCategory([ categoryName => , options => , parentCategoryName => , permissions => , showOrder => ])
#1 */lib/system/package/plugin/AbstractOptionPackageInstallationPlugin.class.php (31):
wcf\system\package\plugin\AbstractOptionPackageInstallationPlugin->importCategories(DOMXPath)
#2 */lib/system/package/PackageInstallationDispatcher.class.php (603):
wcf\system\package\plugin\AbstractOptionPackageInstallationPlugin->install()
#3 */lib/system/package/PackageInstallationDispatcher.class.php (141):
wcf\system\package\PackageInstallationDispatcher->executePIP([ attributes => , pip => , value => ])
#4 */lib/acp/action/InstallPackageAction.class.php (72):
wcf\system\package\PackageInstallationDispatcher->install('986f7f67')
#5 */lib/action/AbstractDialogAction.class.php (68):
wcf\acp\action\InstallPackageAction->stepInstall()
#6 */lib/action/AbstractAction.class.php (47):
wcf\action\AbstractDialogAction->execute()
#7 */lib/system/request/Request.class.php (83):
wcf\action\AbstractAction->__run()
#8 */lib/system/request/RequestHandler.class.php (94):
wcf\system\request\Request->execute()
#9 */acp/index.php (9):
wcf\system\request\RequestHandler->handle('wcf', true)
```

**Comment by gOOvER** [comment] 2017-06-25 15:44
And when i try to deinstall installed Discord API:

`Error

Error Type:
wcf\system\exception\ErrorException
Error Message:
Trying to get property of non-object
File:
*/lib/system/WCF.class.php (311)
Stack Trace:
#0 */lib/system/event/listener/MysteryCodeSpiderRefreshUninstallListener.class.php (19):
wcf\system\WCF::handleError(8, 'Trying to get property of non-object', '*/lib/system/event/listener/MysteryCodeSpiderRefreshUninstallListener.class.php', 19, [ 6 items ])
#1 */lib/system/event/EventHandler.class.php (221):
wcf\system\event\listener\MysteryCodeSpiderRefreshUninstallListener->execute(wcf\acp\action\UninstallPackageAction, 'wcf\\acp\\action\\UninstallPackageAction', 'execute', [ ])
#2 */lib/action/AbstractAction.class.php (102):
wcf\system\event\EventHandler->fireAction(wcf\acp\action\UninstallPackageAction, 'execute')
#3 */lib/action/AbstractDialogAction.class.php (60):
wcf\action\AbstractAction->execute()
#4 */lib/action/AbstractAction.class.php (47):
wcf\action\AbstractDialogAction->execute()
#5 */lib/system/request/Request.class.php (83):
wcf\action\AbstractAction->__run()
#6 */lib/system/request/RequestHandler.class.php (94):
wcf\system\request\Request->execute()
#7 */acp/index.php (9):
wcf\system\request\RequestHandler->handle('wcf', true)`

**Comment by Akizo96** [comment] 2017-06-25 15:45
Have you any plugins installed that also have to do with Discord?  
Would be nice if you could send me the name, thanks :)

**Comment by gOOvER** [comment] 2017-06-25 15:47
Yes. This one:
https://pluginstore.woltlab.com/file/2489-discord-login/

which installs this one:

https://pluginstore.woltlab.com/file/2488-discord-api/

**Comment by Mythen96** [comment] 2017-06-25 15:48
I know that, i mean if you have installed something else that have to do with discord

**Comment by gOOvER** [comment] 2017-06-25 15:48
Only these 2 :)

**Comment by Akizo96** [comment] 2017-06-25 15:59
Sry for the last question that was irrelevant.
I know where the problem is an is fixed with the new upcoming release here on GitHub.
Looks like the system does not pay attention to the excludedpackage section of my API plugin.

**Closed as completed** 2017-06-25 16:28 UTC
